name: Deploy

on:
  push:
    branches:
      - main

      

env:
  CI: false

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Generate PEM
      run: echo "$PEM" >> tcp.pem && chmod 400 tcp.pem
      env:
        PEM: ${{secrets.PEM}}

    - name: Doing the magic now
      run: ssh -i tcp.pem ubuntu@ec2-16-171-64-245.eu-north-1.compute.amazonaws.com "cd /home && sudo mkdir hui && sudo systemctl restart nginx"

    - name: LIVE!!!
      run: echo "Site is Live!🚀🚀🚀"
